# TCL File Generated by Component Editor 16.1
# Sat Sep 16 15:54:24 ICT 2017
# DO NOT MODIFY


# 
# VLC_01 "VLC_01" v1.0
#  2017.09.16.15:54:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VLC_01
# 
set_module_property DESCRIPTION ""
set_module_property NAME VLC_01
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME VLC_01
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL VLC
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file VLC.v VERILOG PATH VLC/VLC.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_reset
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master_read
# 
add_interface avalon_master_read avalon start
set_interface_property avalon_master_read addressUnits SYMBOLS
set_interface_property avalon_master_read associatedClock clock_reset
set_interface_property avalon_master_read associatedReset reset
set_interface_property avalon_master_read bitsPerSymbol 8
set_interface_property avalon_master_read burstOnBurstBoundariesOnly false
set_interface_property avalon_master_read burstcountUnits WORDS
set_interface_property avalon_master_read doStreamReads false
set_interface_property avalon_master_read doStreamWrites false
set_interface_property avalon_master_read holdTime 0
set_interface_property avalon_master_read linewrapBursts false
set_interface_property avalon_master_read maximumPendingReadTransactions 0
set_interface_property avalon_master_read maximumPendingWriteTransactions 0
set_interface_property avalon_master_read readLatency 0
set_interface_property avalon_master_read readWaitTime 1
set_interface_property avalon_master_read setupTime 0
set_interface_property avalon_master_read timingUnits Cycles
set_interface_property avalon_master_read writeWaitTime 0
set_interface_property avalon_master_read ENABLED true
set_interface_property avalon_master_read EXPORT_OF ""
set_interface_property avalon_master_read PORT_NAME_MAP ""
set_interface_property avalon_master_read CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_read SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_read iRData readdata Input 32
add_interface_port avalon_master_read iRd_Data_valid readdatavalid Input 1
add_interface_port avalon_master_read iWait_Rd_Req waitrequest Input 1
add_interface_port avalon_master_read oRead read Output 1
add_interface_port avalon_master_read oRead_Addr address Output 32


# 
# connection point avalon_master_write
# 
add_interface avalon_master_write avalon start
set_interface_property avalon_master_write addressUnits SYMBOLS
set_interface_property avalon_master_write associatedClock clock_reset
set_interface_property avalon_master_write associatedReset reset
set_interface_property avalon_master_write bitsPerSymbol 8
set_interface_property avalon_master_write burstOnBurstBoundariesOnly false
set_interface_property avalon_master_write burstcountUnits WORDS
set_interface_property avalon_master_write doStreamReads false
set_interface_property avalon_master_write doStreamWrites false
set_interface_property avalon_master_write holdTime 0
set_interface_property avalon_master_write linewrapBursts false
set_interface_property avalon_master_write maximumPendingReadTransactions 0
set_interface_property avalon_master_write maximumPendingWriteTransactions 0
set_interface_property avalon_master_write readLatency 0
set_interface_property avalon_master_write readWaitTime 1
set_interface_property avalon_master_write setupTime 0
set_interface_property avalon_master_write timingUnits Cycles
set_interface_property avalon_master_write writeWaitTime 0
set_interface_property avalon_master_write ENABLED true
set_interface_property avalon_master_write EXPORT_OF ""
set_interface_property avalon_master_write PORT_NAME_MAP ""
set_interface_property avalon_master_write CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_write SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_write iWait_Wr_Req waitrequest Input 1
add_interface_port avalon_master_write oWrData writedata Output 32
add_interface_port avalon_master_write oWrite write Output 1
add_interface_port avalon_master_write oWrite_Addr address Output 32


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_reset
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ioGPIO export Bidir 20


# 
# connection point iStart
# 
add_interface iStart conduit end
set_interface_property iStart associatedClock clock_reset
set_interface_property iStart associatedReset reset
set_interface_property iStart ENABLED true
set_interface_property iStart EXPORT_OF ""
set_interface_property iStart PORT_NAME_MAP ""
set_interface_property iStart CMSIS_SVD_VARIABLES ""
set_interface_property iStart SVD_ADDRESS_GROUP ""

add_interface_port iStart iStart export Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_reset
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave iSL_Addr address Input 2
add_interface_port avalon_slave ichipselect chipselect Input 1
add_interface_port avalon_slave iSL_Data writedata Input 32
add_interface_port avalon_slave oSL_Data readdata Output 32
add_interface_port avalon_slave iSL_Read read Input 1
add_interface_port avalon_slave iSL_Write write Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

